export const API_URL = 'http://localhost:8080';
export const RELACAO_TIPO_PARENTESCO_ID = 6;
export const LOG_LEVEL = 'DEBUG';
export const TABLE_TAMANHO_PAGINA_DEFAULT = 10;

export const NATUREZA_JURIDICA_MUNICIPIO = 1244;
export const NATUREZA_JURIDICA_LEGISLATIVO_MUNICIPAL = 1066;
export const NATUREZA_JURIDICA_ESTADO = 1236;
export const NATUREZA_JURIDICA_LEGISLATIVO_ESTADUAL = 1058;
export const NATUREZA_JURIDICA_UNIAO = 1341;
export const NATUREZA_JURIDICA_LEGISLATIVO_FEDERAL = 1040;
